spring.application.name=blog
server.port=${PORT:8081}

#spring.datasource.url=jdbc:h2:file:./data/testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.h2.console.enabled=true
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/blogdb
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect